name: "Terraform"

on:
   pull_request:
     branches:
       - develop
      
permissions:
  contents: write
  
jobs:
  tfsec:
    name: tfsec
    runs-on: ubuntu-latest
    env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Terraform security scan
        uses: triat/terraform-security-scan@v3.0.0
